blank_issues_enabled: false
contact_links:
  - name: 💡 Request a feature
    url: https://github.com/helenvholmes/bookbox/discussions/categories/feature-requests
    about: Suggest an idea, or upvote one that's already there.
